export const WEDDING = {
  groom: {
    name: 'Bùi Duy Quý',
    shortName: 'Duy Quý',
    nameParts: ['Bùi', 'Duy Quý'],
    role: 'Chú Rể · The Groom',
    parents: ['Bùi Lai', 'Nguyễn Thị Bạch Liền'],
    hometown: 'TP. Quảng Ngãi',
    photo: '/images/wedding/chu-re.jpg',
  },
  bride: {
    name: 'Phạm Thị Sương Sương',
    shortName: 'Sương Sương',
    nameParts: ['Phạm Thị', 'Sương Sương'],
    role: 'Cô Dâu · The Bride',
    parents: ['Phạm Trọng Tùng', 'Cao Thị Thắm'],
    hometown: 'TP. Vũng Tàu',
    photo: '/images/wedding/co-dau.jpg',
  },
  date: {
    display: '07 · 06 · 2026',
    iso: '2026-06-07T11:30:00+07:00',
    dayOfWeek: 'Chủ Nhật',
    day: '07',
    month: 'Tháng 06',
    year: '2026',
    lunar: 'Tức ngày 22 tháng 04 năm Bính Ngọ',
    receptionStart: '11:00',
    ceremonyStart: '11:30',
  },
  venue: {
    name: 'Nhà Hàng Maxim\'s',
    address: '36 Nguyễn Thái Học, Phường 7',
    city: 'TP. Vũng Tàu',
    mapSrc: 'https://maps.google.com/maps?q=36+Nguyễn+Thái+Học,+Phường+7,+Vũng+Tàu&output=embed',
    mapsUrl: 'https://www.google.com/maps/search/36+Nguyễn+Thái+Học+Phường+7+Vũng+Tàu',
  },
  gallery: [
    { src: 'public/images/wedding/chu-re.jpg', alt: 'Khoảnh khắc 1' },
    { src: 'public/images/wedding/chu-re.jpg', alt: 'Khoảnh khắc 2' },
    { src: 'public/images/wedding/co-dau.jpg', alt: 'Khoảnh khắc 3' },
    { src: 'public/images/wedding/co-dau.jpg', alt: 'Khoảnh khắc 4' },
    { src: 'public/images/wedding/co-dau.jpg', alt: 'Khoảnh khắc 5' },
    { src: 'public/images/wedding/co-dau.jpg', alt: 'Khoảnh khắc 6' },
    { src: 'public/images/wedding/co-dau.jpg', alt: 'Khoảnh khắc 7' },
  ],
  cover: {
    bgImage: '/images/wedding/background.jpg',
    eyebrow: 'Thân Mời · Wedding Invitation',
    inviteText: 'Trân trọng kính mời',
    btnText: 'Mở Thiệp · Open',
  },
}
